#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/repo -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# Check if the directory is a Git repository
is_git_repo=false
if [[ -d "$selected/.git" ]]; then
    is_git_repo=true
fi

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    # Create a new tmux session if not running inside tmux
    tmux new-session -s $selected_name -c $selected -d
    [[ $is_git_repo == true ]] && tmux new-window -t $selected_name:1 -c $selected -n lazygit lazygit
    tmux rename-window -t $selected_name:0 nvim
    tmux send-keys -t $selected_name:0 "nvim" C-m
    tmux attach-session -t $selected_name
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    # Create a detached tmux session
    tmux new-session -ds $selected_name -c $selected
    [[ $is_git_repo == true ]] && tmux new-window -t $selected_name:1 -c $selected -n lazygit lazygit
    tmux rename-window -t $selected_name:0 nvim
    tmux send-keys -t $selected_name:0 "nvim" C-m
fi

# Switch to the session
tmux select-window -t $selected_name:0
tmux switch-client -t $selected_name
